# Generated by Django 4.2.2 on 2023-08-12 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('long_url', models.CharField(unique=True)),
                ('short_url', models.CharField(unique=True)),
                ('slug', models.CharField(max_length=8, unique=True)),
                ('no_of_uses', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
