# Generated by Django 4.2.2 on 2023-08-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitLink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='urldata',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
