# Generated by Django 4.2.2 on 2023-07-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogsentrymodel',
            name='module',
            field=models.CharField(default='def'),
            preserve_default=False,
        ),
    ]
